controllers:
  resource: ../src/Controller/
  type: attribute

index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: pages/index.html.twig
