name: CI

on:
  push: ~
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          ini-values: display_errors=On
          extensions: xml, zip
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          CACHE_NAME: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-
      - name: Install JS dependencies
        run: npm install
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        env:
          CACHE_NAME: composer
        with:
          path: vendor
          key: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-
      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      - name: Build site
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          npm run prod
          vendor/bin/jigsaw build production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/build_production
          cname: mobilesacn.dankeenan.org
