name: CI

on:
  push: ~
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          ini-values: display_errors=On
          extensions: xml, zip
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          CACHE_NAME: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-
      - name: Install JS dependencies
        run: npm install
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        env:
          CACHE_NAME: composer
        with:
          path: vendor
          key: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-${{ env.CACHE_NAME }}-
      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      - name: Build site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          bin/console dump-static-site
      - name: Upload built website
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ${{ github.workspace }}/output
          if-no-files-found: error

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3
        id: download
        with:
          name: website
          path: public
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{steps.download.outputs.download-path}}
          cname: mobilesacn.dankeenan.org
